package:
  name: trivial-indent
  version: "0.0.0.2026.09.12"

source:
  git: https://codeberg.org/shinmera/trivial-indent.git
  rev: 7281fb015c573c35a3a25392f3019c5e32fe0bd0
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "trivial-indent")'

about:
  repository: https://codeberg.org/shinmera/trivial-indent.git
  homepage: https://shinmera.com/docs/trivial-indent/
  documentation: https://shinmera.com/docs/trivial-indent/
  license: Zlib
  summary: A very simple common lisp library to allow indentation hints for SWANK. 
  description: |
    This allows you to define custom indentation hints for your macros if the
    one recognised by Slime, Sly, or other editors automatically produces
    unwanted results.

    See [the docs](https://shinmera.com/docs/trivial-indent/) for more details.
