package:
  name: net.didierverna.asdf-flv
  version: "2.2"

source:
  git: https://github.com/didierverna/asdf-flv
  rev: 3f1de416f7f40a39c47f08335c710a884ece36b3
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive --eval '(require :asdf)' --eval '(asdf:load-system "net.didierverna.asdf-flv")'

about:
  repository: https://github.com/didierverna/asdf-flv
  homepage: https://github.com/didierverna/asdf-flv
  license: FSFAP
  summary: ASDF extension to provide support for file-local variables
  description: |
    ASDF-FLV provides support for file-local variables through ASDF. A
    file-local variable behaves like *PACKAGE* and *READTABLE* with respect to LOAD
    and COMPILE-FILE: a new dynamic binding is created before processing the file,
    so that any modification to the variable becomes essentially file-local.

    In order to make one or several variables file-local, use the macros
    SET-FILE-LOCAL-VARIABLE(S).
