package:
  name: cl-who
  version: "1.1.5"

source:
  git: https://github.com/edicl/cl-who
  rev: 819de0f9e250185ecef3511caf6aea6a25845a1c
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "cl-who")'
          --eval '(asdf:test-system "cl-who")'
    requirements:
      run:
        - flexi-streams

about:
  repository: https://github.com/edicl/cl-who
  homepage: https://edicl.github.io/cl-who/
  license: BSD-2-Clause
  summary: Yet another Common Lisp markup language
  description: |
    There are plenty of [Lisp Markup Languages](http://www.cliki.net/Lisp%20Markup%20Languages) out there - every Lisp programmer seems to write at least one during his career - and CL-WHO (where _WHO_ means "with-html-output" for want of a better acronym) is probably just as good or bad as the next one. They are all more or less similar in that they provide convenient means to convert S-expressions intermingled with code into (X)HTML, XML, or whatever but differ with respect to syntax, implementation, and API. So, if you haven't made a choice yet, check out the alternatives as well before you begin to use CL-WHO just because it was the first one you came across. (Was that repelling enough?) If you're looking for a slightly different approach you might also want to look at [HTML-TEMPLATE](http://weitz.de/html-template/).

    I wrote this one in 2002 although at least Tim Bradshaw's [htout](http://www.cliki.net/htout) and [AllegroServe's HTML generation facilities](http://opensource.franz.com/aserve/aserve-dist/doc/htmlgen.html) by John Foderaro of Franz Inc. were readily available. Actually, I don't remember why I had to write my own library - maybe just because it was fun and didn't take very long. The syntax was obviously inspired by htout although it is slightly different.

    CL-WHO tries to create efficient code in that it makes constant strings as long as possible. In other words, the code generated by the CL-WHO macros will usually be a sequence of `WRITE-STRING` forms for constant parts of the output interspersed with arbitrary code inserted by the user of the macro. CL-WHO will make sure that there aren't two adjacent `WRITE-STRING` forms with constant strings. CL-WHO's output is either XHTML (default), 'plain' (SGML) HTML or HTML5 (using HTML syntax) — depending on what you've set [`HTML-MODE`](https://edicl.github.io/cl-who/#html-mode) to.

    CL-WHO is intended to be portable and should work with all conforming Common Lisp implementations. [Let us know](https://edicl.github.io/cl-who/#mail) if you encounter any problems.

    It comes with a [BSD-style license](http://www.opensource.org/licenses/bsd-license.php) so you can basically do with it whatever you want.
