package:
  name: trivial-with-current-source-form
  version: "0.0.0.2025.11.12"

source:
  git: https://github.com/scymtym/trivial-with-current-source-form
  rev: d00f7abcbb127969884ea639a334827c3b5a0ad2
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "trivial-with-current-source-form")'

about:
  repository: https://github.com/scymtym/trivial-with-current-source-form
  homepage: https://github.com/scymtym/trivial-with-current-source-form
  documentation: https://github.com/scymtym/trivial-with-current-source-form/blob/master/README.org
  license: MIT
  summary: Helps Common Lisp macro writers produce better errors for macro users
  description: |
    This library allows macro writers to provide better feedback to macro users
    when errors are signaled during macroexpansion.

    > Note: While this library can be loaded into and used in any Common Lisp
    > implementation, the improved behavior described below is only available in
    > [CLASP](https://github.com/clasp-developers/clasp) and
    > [SBCL](http://www.sbcl.org/) (only in versions 1.3.13 and newer).


        (with-current-source-form (FORM &REST FORMS) &BODY BODY)

    In a macroexpander, indicate that FORM, FORMS are being processed by BODY.

    FORMS are usually sub-forms of the whole form passed to the expander.

    If more than one form is supplied, FORMS should be ordered by
    specificity, with the most specific form first. This allows the
    compiler to try and obtain a source path using subsequent elements of
    FORMS if it fails for the first one.

    Indicating the processing of sub-forms lets the compiler report
    precise source locations in case conditions are signaled during the
    execution of BODY.

    See [the README](https://github.com/scymtym/trivial-with-current-source-form/blob/master/README.org) for more details.
