package:
  name: closer-mop
  version: "0.0.0.2026.08.29"

source:
  git: https://codeberg.org/pcostanza/closer-mop.git
  rev: 8151e406a47e5d60b54c99f2ab965cbc70df4ef0
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive --eval '(require :asdf)' --eval '(asdf:load-system "closer-mop")'

about:
  repository: https://codeberg.org/pcostanza/closer-mop.git
  homepage: https://codeberg.org/pcostanza/closer-mop
  license: MIT
  summary: |
    Closer to MOP is a compatibility layer that rectifies many of the absent or
    incorrect CLOS MOP features across a broad range of Common Lisp
    implementations.
  description: |
    Closer to MOP is a compatibility layer that rectifies many of the absent or
    incorrect CLOS MOP features across a broad range of Common Lisp
    implementations.
