package:
  name: cl-autoload
  version: "0.0.0.2026.07.27"

source:
  git: https://github.com/melisgl/autoload
  rev: 452ccdf4bd1eae4abe8db4501d178005117e4815
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf
    - closer-mop
    - mgl-pax-bootstrap
    - trivial-indent

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "autoload")'

about:
  repository: https://github.com/melisgl/autoload
  homepage: https://github.com/melisgl/autoload
  documentation: https://fixnum.com/autoload-manual.html
  license: MIT
  summary: Autoloading facility for Common Lisp
  description: |
    Libraries often choose to limit dependencies, even if it means sacrificing
    features or duplicating code, to minimize

      - compilation time,
      - memory usage in deployment, and
      - the risk of breakage through dependencies.

    Autoload mitigates these issues by loading heavy dependencies on demand. The
    core idea is

        (defmacro autoload (name asdf-system)
          `(defun ,name (&rest args)
             (asdf:load-system ,asdf-system)
             (apply ',name args)))

    Suppose we have a library called `my-lib` that autoloads `my-lib/full`. In
    `my-lib`, we could use `AUTOLOAD` as

        (autoload foo "my-lib/full")

    and have

        (defun foo (x)
          "doc"
          (1+ x))

    in `my-lib/full`.

    However, manually keeping the
    [loaddef](https://github.com/melisgl/autoload#x-28AUTOLOAD-3A-40LOADDEF-20MGL-PAX-3AGLOSSARY-TERM-29)s (e.g. the `AUTOLOAD` form above) in sync with the definitions is
    fragile, so we introduce the
    [`DEFUN/AUTO`](https://github.com/melisgl/autoload#x-28AUTOLOAD-3ADEFUN-2FAUTO-20MGL-PAX-3AMACRO-29)
    [autodef](https://github.com/melisgl/autoload#x-28AUTOLOAD-3A-40AUTODEF-20MGL-PAX-3AGLOSSARY-TERM-29) to mark autoloaded functions in the `my-lib/full` system:

        (defun/auto foo (x)
          "doc"
          (1+ x))

