package:
  name: cl-cffi
  version: "0.24.1.2026.08.21"

source:
  git: https://github.com/cffi/cffi
  rev: 787d3cd94404f85c0324b0f8d6b9c535fc091720
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf
    - alexandria
    - trivial-features
    - cl-babel
    - ${{ compiler('c') }}
    - libffi

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "trivial-features-tests")'
          --eval '(asdf:test-system "trivial-features")'
          --eval '(handler-bind ((style-warning (function muffle-warning)))
                    (asdf:load-system "cffi-tests")
                    (asdf:test-system "cffi"))'

    requirements:
      run:
        - cl-rt
        - bordeaux-threads

about:
  repository: https://github.com/cffi/cffi
  homepage: https://cffi.common-lisp.dev/
  license: "MIT"
  documentation: https://cffi.common-lisp.dev/manual/index.html
  summary: Common Foreign Function Interface for Common Lisp
  description: |
    **What**

    CFFI, the Common Foreign Function Interface, purports to be a portable FFI
    for Common Lisp. It abstracts away the differences between the API of the
    native FFI's of the various Common Lisp implementations.

    **How**

    The CFFI library is composed of a Lisp-implementation-specific backend in
    the CFFI-SYS package, and a portable frontend in the CFFI package.

    The CFFI-SYS backend package defines a low-level interface to the native FFI
    support in the Lisp implementation. It offers operators for allocating and
    dereferencing foreign memory, calling foreign functions, and loading shared
    libraries.

    The CFFI frontend provides a more comfortable, declarative interface for
    defining foreign functions, structures, typedefs, enumerated types, etc. It
    is implemented in portable ANSI CL making use of the low-level operators
    exported by CFFI-SYS.

    The CFFI-LIBFFI subsystem loads support for passing structs by value. It
    requires [libffi](https://sourceware.org/libffi/) for that.

    Please consult [the
    manual](http://common-lisp.net/project/cffi/manual/html_node/) for further
    details, including installation instructions.
