package:
  name: cl-html-encode
  version: "0.0.0.2004.07.07"

source:
  - path: html-encode.lisp
  - path: html-encode.asd

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "html-encode")'

about:
  documentation: https://cliki.net/html-encode
  license: MIT
  summary: Small Common Lisp library for encoding text into various web-savvy formats.
  description: |
    html-encode is a small library for encoding [text](https://cliki.net/text) in various [web](https://cliki.net/web)\-savvy formats. These are the functions exported from the html-encode package:
    
    -   **encode-for-pre** - encodes text so it's suitable for inclusion in a [HTML](https://cliki.net/HTML) PRE element, or in a regular tag with HTML spacing.
    -   **encode-for-argument** does the same thing as **encode-for-pre**, except it also encodes quotation marks as SGML &quot; so they can be used in HTML element attributes.
    -   **encode-for-tt** - attemps to encode the text so it can display in a TT element with proper spacing. The keyword argument first-char-nbsp controls whether the first character should be rendered as a non-breaking space if it is a space in the input text.
    -   **encode-for-http** - A highly misnamed function which does nothing of the sort. It breaks the string on the ends of tags so that long lines aren't sent.
