package:
  name: trivial-garbage
  version: "0.0.0.2026.08.29"

source:
  git: https://github.com/trivial-garbage/trivial-garbage.git
  rev: f0663f7b0c900ed78ac19f6db306e7c6cac999fd
  submodules: false

build:
  noarch: generic
  script: build.sh

requirements:
  run:
    - sbcl
    - cl-asdf

tests:
  - script:
      - sbcl --no-userinit --non-interactive
          --eval '(require :asdf)'
          --eval '(asdf:load-system "trivial-garbage")'
          --eval '(asdf:test-system "trivial-garbage")'
    requirements:
      run:
        - cl-rt

about:
  repository: https://github.com/trivial-garbage/trivial-garbage.git
  homepage: https://trivial-garbage.common-lisp.dev/
  documentation: https://trivial-garbage.common-lisp.dev/
  license: MIT
  summary: Portable GC-related APIs for Common Lisp.
  description: |
    [trivial-garbage](http://common-lisp.net/project/trivial-garbage) provides a
    portable API to finalizers, weak hash-tables and weak pointers on all major
    implementations of the Common Lisp programming language. For a good
    introduction to these data-structures, have a look at [Weak References: Data
    Types and
    Implementation](http://www.haible.de/bruno/papers/cs/weak/WeakDatastructures-writeup.html)
    by Bruno Haible.

    Also see [the documentation](https://trivial-garbage.common-lisp.dev/).
